version: "3.9"

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    restart: always
    container_name: goormthon-db
    environment:
      MYSQL_ROOT_PASSWORD: youngh29ktj!
      MYSQL_DATABASE: goormthon
    ports:
      - "3307:3306"
    networks:
      - app-network

networks:
  app-network: