services:
  backend:
    image: minwu1234/9roomthon-4-team:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h goormthon-db -uroot -p1234" ]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: goormthon-db
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=sample
      - MYSQL_USER=userab
      - MYSQL_PASSWORD=12345
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:




